# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'QuandooTest' do
   use_frameworks!
  # Pods for QuandooTest
   post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '3.0'
          end
      end
   end
    pod 'JSONJoy-Swift', '~> 2.0.1'
    pod 'AFNetworking', '~> 3.0'
    pod "NVActivityIndicatorView"
end
